spring:
  application:
    name: launchpad
server:
  port: 8080
  http2:
    enabled: true
version: ${VERSION:unknown}

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    root: ERROR
auth-config:
  organization-id: ${ORGANIZATION_ID:}
  identity-provider-url: ${IDENTITY_PROVIDER_URL:}
asset-config:
  js: https://sc-static.net/scevent.min.js
  js-refresh-hours: 1
  root-doc: /static/readme.html

---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    root: INFO
asset-config:
  js: /static/scevent.min.js
  js-refresh-hours: 1
  root-doc: /static/readme.html

---
spring:
  config:
    activate:
      on-profile: mpc-aws
batch-config:
  job-queue-arn: ${MPC_AWS_BATCH_JOB_QUEUE_ARN:}
  job-role-arn: ${MPC_AWS_BATCH_JOB_ROLE_ARN:}
  image-name: gcr.io/snap-launchpad-public/snappcs/onedocker:prod
  advertiser-url: https://aws.api.snapchat.com/pet/v1/mpc/lift

---
spring:
  config:
    activate:
      on-profile: mpc-gcp
batch-config:
  instance-template: ${MPC_GCP_BATCH_INSTANCE_TEMPLATE:}
  image-name: gcr.io/snap-launchpad-public/snappcs/onedocker:prod
  advertiser-url: https://gcp.api.snapchat.com/pet/v1/mpc/lift

---
spring:
  config:
    activate:
      on-profile: conversion-log
  servlet:
    multipart:
      resolve-lazily: true

storage-config:
  storage-prefix: ${STORAGE_PREFIX:file:///tmp}

---
spring:
  config:
    activate:
      on-profile: conversion-relay
relay-config:
  pixel-path: /gateway/p
  pixel-server-host: tr.snapchat.com
  pixel-server-test-host: tr-shadow.snapchat.com
  v2-conversion-path: /v2/conversion
