spring:
  application:
    name: launchpad
server:
  port: 8080
  http2:
    enabled: true
version: ${VERSION:unknown}
asset-config:
  root-doc: /static/readme.html

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    root: ERROR
auth-config:
  organization-id: ${ORGANIZATION_ID:}
  identity-provider-url: ${IDENTITY_PROVIDER_URL:}

---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: mpc-aws
batch-config:
  job-queue-arn: ${MPC_AWS_BATCH_JOB_QUEUE_ARN:}
  job-role-arn: ${MPC_AWS_BATCH_JOB_ROLE_ARN:}
  publisher-url: ${MPC_JOB_CONFIG_PUBLISHER_URL:}
  image-name: ${MPC_JOB_IMAGE:}

---
spring:
  config:
    activate:
      on-profile: mpc-gcp
batch-config:
  instance-template: ${MPC_GCP_BATCH_INSTANCE_TEMPLATE:}
  publisher-url: ${MPC_JOB_CONFIG_PUBLISHER_URL:}
  image-name: ${MPC_JOB_IMAGE:}

---
spring:
  config:
    activate:
      on-profile: conversion-log
  servlet:
    multipart:
      resolve-lazily: true
storage-config:
  storage-prefix: ${STORAGE_PREFIX:file:///tmp}
  logging-prefix: logs
  adhoc-prefix: files

---
spring:
  config:
    activate:
      on-profile: conversion-relay
relay-config:
  pixel-path: /gateway/p
  pixel-server-host: tr.snapchat.com
  pixel-server-test-host: tr-shadow.snapchat.com
  v2-conversion-path: /v2/conversion
relay-asset-config:
  js: ${RELAY_JS_ASSET_URL:/static/scevent.min.js}
  js-refresh-hours: 1
