spring:
  application:
    name: launchpad
server:
  port: 8080
version: ${VERSION:unknown}
<<<<<<< Updated upstream
=======
organization-id: ${ORGANIZATION_ID:.}
>>>>>>> Stashed changes

---
spring:
  config:
    activate:
      on-profile: prod
asset-config:
  js: https://sc-static.net/scevent.min.js
  js-refresh-hours: 1
  root-doc: /static/readme.html
auth:
  public-key-url: https://storage.googleapis.com/snap-launchpad-public/certificate/jwks.json

---
spring:
  config:
    activate:
      on-profile: dev
asset-config:
  js: /static/scevent.min.js
  js-refresh-hours: 1
  root-doc: /static/readme.html
auth:
  public-key-url: classpath:auth/jwks.json

---
spring:
  config:
    activate:
      on-profile: batch-aws
batch-config:
  cloud-platform: AWS
  execution-role-arn: ${AWS_BATCH_EXECUTION_ROLE_ARN}
  job-role-arn: ${AWS_BATCH_JOB_ROLE_ARN}
  job-queue: ${AWS_BATCH_JOB_QUEUE}
  volume: ${AWS_VOLUME}

---
spring:
  config:
    activate:
      on-profile: batch-gcp
batch-config:
  cloud-platform: GCP
  project-id: ${GCP_PROJECT_ID}
  region: ${GCP_REGION}
  storage-bucket: ${GCP_STORAGE_BUCKET}
  instance-template: ${GCP_BATCH_INSTANCE_TEMPLATE}

---
spring:
  config:
    activate:
      on-profile: conversion-log
log-config:
  storage-path: ${STORAGE_PATH}

---
spring:
  config:
    activate:
      on-profile: conversion-relay
relay-config:
  pixel-path: /gateway/p
  pixel-server-host: tr.snapchat.com
  pixel-server-test-host: tr-shadow.snapchat.com
  v2-conversion-path: /v2/conversion
