AWSTemplateFormatVersion: 2010-09-09
Resources:
  Launchpad:
    Type: AWS::AppRunner::Service
    Properties:
      SourceConfiguration:
        ImageRepository:
          ImageIdentifier: public.ecr.aws/f0q4i5h2/launchpad:latest
          ImageRepositoryType: ECR_PUBLIC
          ImageConfiguration:
            RuntimeEnvironmentVariables:
              - Name: SPRING_PROFILES_ACTIVE
                Value: prod,conversion-relay
              - Name: RELAY_JS_ASSET_URL
                Value: https://sc-static.net/scevent.min.js
Outputs:
  Launchpad:
    Description: The created service.
    Value: !GetAtt Launchpad.ServiceUrl
