AWSTemplateFormatVersion: 2010-09-09
Parameters:
  OrganizationID:
    Type: String
    Description: Your organization id in Snapchat Business Manager. See https://businesshelp.snapchat.com/s/article/biz-acct-id?language=en_US for more information
Resources:
  LaunchpadRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - ecs-tasks.amazonaws.com
                - tasks.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSBatchFullAccess
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  LaunchpadRolePassSelfPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource: !GetAtt LaunchpadRole.Arn
      PolicyName: LaunchpadRolePassSelfPolicy
      Roles:
        - !Ref LaunchpadRole

  EcsInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref LaunchpadRole

  BatchJobVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  BatchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Batch Security Group
      VpcId: !Ref BatchJobVPC

  BatchJobSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BatchJobVPC
      CidrBlock: !GetAtt BatchJobVPC.CidrBlock
      MapPublicIpOnLaunch: true

  BatchJobInternetGateway:
    Type: AWS::EC2::InternetGateway

  BatchJobInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref BatchJobVPC
      InternetGatewayId: !Ref BatchJobInternetGateway

  BatchJobRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref BatchJobVPC

  BatchJobRoute:
    Type: AWS::EC2::Route
    DependsOn:
      - BatchJobInternetGatewayAttachment
    Properties:
      RouteTableId: !Ref BatchJobRouteTable
      GatewayId: !Ref BatchJobInternetGateway
      DestinationCidrBlock: 0.0.0.0/0

  BatchJobSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref BatchJobRouteTable
      SubnetId: !Ref BatchJobSubnet

  BatchJobComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeResources:
        InstanceRole: !Ref EcsInstanceProfile
        MaxvCpus: 1024
        MinvCpus: 0
        InstanceTypes:
          - optimal
        Subnets:
          - !Ref BatchJobSubnet
        Type: EC2
        SecurityGroupIds:
          - !Ref BatchSecurityGroup

  BatchJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchJobComputeEnvironment
      State: ENABLED
      Priority: 1

  LaunchpadStorage:
    Type: AWS::S3::Bucket

  Launchpad:
    Type: AWS::AppRunner::Service
    Properties:
      SourceConfiguration:
        ImageRepository:
          ImageIdentifier: public.ecr.aws/f0q4i5h2/launchpad:latest
          ImageRepositoryType: ECR_PUBLIC
          ImageConfiguration:
            RuntimeEnvironmentVariables:
              - Name: SPRING_PROFILES_ACTIVE
                Value: prod,conversion-log,mpc-aws
              - Name: ORGANIZATION_ID
                Value: !Ref OrganizationID
              - Name: IDENTITY_PROVIDER_URL
                Value: https://aws.api.snapchat.com/pet/v1/authorization
              - Name: STORAGE_PREFIX
                Value: !Sub s3://${LaunchpadStorage}
              - Name: MPC_AWS_BATCH_JOB_QUEUE_ARN
                Value: !Ref BatchJobQueue
              - Name: MPC_AWS_BATCH_JOB_ROLE_ARN
                Value: !GetAtt LaunchpadRole.Arn
              - Name: MPC_JOB_CONFIG_PUBLISHER_URL
                Value: https://aws.api.snapchat.com/pet/v1/mpc/job-configs
              - Name: MPC_JOB_PUBLISHER_URL
                Value: https://aws.api.snapchat.com/pet/v1/mpc/jobs
              - Name: MPC_JOB_IMAGE
                Value: gcr.io/snap-launchpad-public/snap-mpc/onedocker:554d7282c7cfc74841d764ddaf44c736f3652fd7
              - Name: MPC_JOB_TIMEOUT
                Value: 43200
      InstanceConfiguration:
        InstanceRoleArn: !GetAtt LaunchpadRole.Arn

Outputs:
  Launchpad:
    Description: The created service.
    Value: !GetAtt Launchpad.ServiceUrl
