AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  OrganizationID:
    Type: String
    Description: Your organization id in Snapchat Business Manager. See https://businesshelp.snapchat.com/s/article/biz-acct-id?language=en_US for more information
Resources:
  LaunchpadRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: tasks.apprunner.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSBatchFullAccess
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  LaunchpadRolePassSelfPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource: !GetAtt LaunchpadRole.Arn
      PolicyName: LaunchpadRolePassSelfPolicy
      Roles:
        - !Ref LaunchpadRole

  BatchJobVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  BatchJobSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BatchJobVPC
      CidrBlock: 10.0.0.0/16
      MapPublicIpOnLaunch: true

  BatchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Batch Security Group
      VpcId: !Ref BatchJobVPC

  BatchJobComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeResources:
        InstanceRole: !Ref LaunchpadRole
        MaxvCpus: 1024
        MinvCpus: 0
        InstanceTypes:
          - optimal
        Subnets:
          - !Ref BatchJobSubnet
        Type: EC2
        SecurityGroupIds:
          - !Ref BatchSecurityGroup

  BatchJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchJobComputeEnvironment
      State: ENABLED
      Priority: 1

  LaunchpadStorage:
    Type: AWS::S3::Bucket

  Launchpad:
    Type: AWS::AppRunner::Service
    Properties:
      SourceConfiguration:
        ImageRepository:
          ImageIdentifier: public.ecr.aws/f0q4i5h2/launchpad:latest
          ImageRepositoryType: ECR_PUBLIC
          ImageConfiguration:
            RuntimeEnvironmentVariables:
              - Name: SPRING_PROFILES_ACTIVE
                Value: prod,conversion-log,mpc-aws
              - Name: ORGANIZATION_ID
                Value: !Ref OrganizationID
              - Name: IDENTITY_PROVIDER_URL
                Value: https://aws.api.snapchat.com/pet/v1/authorization
              - Name: STORAGE_PREFIX
                Value: !Sub s3://${LaunchpadStorage}
              - Name: MPC_AWS_BATCH_JOB_QUEUE_ARN
                Value: !Ref BatchJobQueue
              - Name: MPC_AWS_BATCH_JOB_ROLE_ARN
                Value: !GetAtt LaunchpadRole.Arn
      InstanceConfiguration:
        InstanceRoleArn: !GetAtt LaunchpadRole.Arn

Outputs:
  Launchpad:
    Description: The created service.
    Value: !GetAtt Launchpad.ServiceUrl
