name: 'Update aws cloudformation'

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  upload-cloudformation-to-s3:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: [relay] Update docker image url in cloudformation yml file
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.Mappings.ecsTaskDefMap.variables.dockerImage = "gcr.io/snap-launchpad-public/launchpad/aws:${{ github.ref_name }}"' 'deployment/aws/template-relay.yml'

      - name: [relay] Update environment variable VERSION in cloudformation yml file
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '(.Resources.ECSTaskDefinition.Properties.ContainerDefinitions[0].Environment[0] | select(.Name == "VERSION") | .Value) = "${{ github.ref_name }}"' 'deployment/aws/template-relay.yml'

      - name: [mpc] Update docker image url in cloudformation yml file
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.Mappings.ecsTaskDefMap.variables.dockerImage = "gcr.io/snap-launchpad-public/launchpad/aws:${{ github.ref_name }}"' 'deployment/aws/template-mpc.yml'

      - name: [mpc] Update environment variable VERSION in cloudformation yml file
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '(.Resources.ECSTaskDefinition.Properties.ContainerDefinitions[0].Environment[0] | select(.Name == "VERSION") | .Value) = "${{ github.ref_name }}"' 'deployment/aws/template-mpc.yml'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-skip-session-tagging: true

      - name: Copy relay cloudformation to S3 with the AWS CLI
        run: |
          aws s3 cp deployment/aws/template-relay.yml s3://snap-launchpad-public/cloudformation/template-relay.yml

      - name: Copy mpc cloudformation to S3 with the AWS CLI
        run: |
          aws s3 cp deployment/aws/template-mpc.yml s3://snap-launchpad-public/cloudformation/template-mpc.yml