name: 'Update aws cloudformation'

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  upload-cloudformation-to-s3:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update docker image url in relay cloudformation yml file
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.Resources.Launchpad.Properties.SourceConfiguration.ImageRepository.ImageIdentifier = "public.ecr.aws/f0q4i5h2/launchpad:${{ github.ref_name }}"' 'deployment/aws/template-relay.yml'

      - name: Update docker image url in mpc cloudformation yml file
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.Mappings.ecsTaskDefMap.variables.dockerImage = "public.ecr.aws/f0q4i5h2/launchpad:${{ github.ref_name }}"' 'deployment/aws/template-mpc.yml'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::710089059969:role/_Snap_GitHubActions
          role-duration-seconds: 1200
          role-session-name: GitHubActionsSession

      - name: Copy relay cloudformation to S3 with the AWS CLI
        run: |
          aws s3 cp deployment/aws/template-relay.yml s3://snap-launchpad-public/cloudformation/template-relay.yml

      - name: Copy mpc cloudformation to S3 with the AWS CLI
        run: |
          aws s3 cp deployment/aws/template-mpc.yml s3://snap-launchpad-public/cloudformation/template-mpc.yml
