name: 'Update gcp cloud shell image'

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  publish-gcp-cloudshell-image-to-gcr-relay:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v6
        with:
          remove-dotnet: 'true'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: 'gcr.io'
          username: '_json_key'
          password: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: deployment/gcp
          push: true
          tags: gcr.io/snap-launchpad-public/launchpad-cloud-shell/relay:prod
          build-args: |
            LAUNCHPAD_MODE=relay
            VERSION=${{ github.ref_name }}

  publish-gcp-cloudshell-image-to-gcr-mpc:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: 'gcr.io'
          username: '_json_key'
          password: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: deployment/gcp
          push: true
          tags: gcr.io/snap-launchpad-public/launchpad-cloud-shell/mpc:prod
          build-args: |
            LAUNCHPAD_MODE=mpc
            VERSION=${{ github.ref_name }}
