name: 'Release new launchpad image'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  publish-gcp-launchpad-image-to-gcr:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: 'gcr.io'
          username: '_json_key'
          password: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Deploy gcp with commit sha
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          ./deploy.sh gcp ${{ github.sha }}

      - name: Deploy gcp with release tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./deploy.sh gcp ${{ github.ref_name }}

      - name: Deploy aws with commit sha
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          ./deploy.sh aws ${{ github.sha }}

      - name: Deploy aws with release tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./deploy.sh aws ${{ github.ref_name }}
