name: 'Build Launchpad'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Gradle Spotless
        run: ./gradlew :spotlessApply

      - name: Gradle build
        run: ./gradlew build

      - name: Gradle test
        run: ./gradlew test
